stages:          
  - build
  
build-linux-x64:   
  stage: build
  image: $CI_SERVER_HOST:5050/libretro-build-rust:latest 
  tags:
    - linux    
  script:
    - cargo build --release
    - cp target/release/libholani_retro.so holani_libretro-linux-x86_64.so
  artifacts:
    paths:
    - holani_libretro-linux-x86_64.so

build-windows-x86_64:   
  stage: build
  image: $CI_SERVER_HOST:5050/libretro-build-rust:latest 
  tags:
    - linux
  script:
    - cargo build --release --target x86_64-pc-windows-gnu
    - cp target/x86_64-pc-windows-gnu/release/holani_retro.dll holani_libretro-windows-x86_64.dll
  artifacts:
    paths:
    - holani_libretro-windows-x86_64.dll

build-osx-x86_64:   
  stage: build
  image: $CI_SERVER_HOST:5050/libretro-build-rust-osx:latest  
  tags:
    - linux
  script:
    - cargo build --release --target x86_64-apple-darwin
    - cp target/x86_64-apple-darwin/release/libholani_retro.dylib holani_libretro-osx-x86_64.dylib
  artifacts:
    paths:
    - holani_libretro-osx-x86_64.dylib

build-osx-aarch64:   
  stage: build
  image: $CI_SERVER_HOST:5050/libretro-build-rust-osx:latest
  tags:
    - linux      
  script:
    - cargo build --release --target aarch64-apple-darwin
    - cp target/aarch64-apple-darwin/release/libholani_retro.dylib holani_libretro-osx-aarch64.dylib
  artifacts:
    paths:
    - holani_libretro-osx-aarch64.dylib

build-linux-android:   
  stage: build
  image: $CI_SERVER_HOST:5050/libretro-build-rust-android:latest
  tags:
    - linux
  script:   
    - cargo ndk -o ./jniLibs build --release
    - cp jniLibs/arm64-v8a/libholani_retro.so holani_libretro-android-arm64-v8a.so
    - cp jniLibs/armeabi-v7a/libholani_retro.so holani_libretro-android-armeabi-v7a.so
  artifacts:
    paths:
    - holani_libretro-android-arm64-v8a.so
    - holani_libretro-android-armeabi-v7a.so